### ISSUE TITLE
მოკავშირე ფილდების მოდელის დასაწყისში ერთად ჩაწერა ამარტივებს მომავალში ამ ფილდების მოძებნას და თან სტრუქტურულადაც უფრო გამართულია

### ISSUE THREAD

**Issue by MariamKipshidze** [lost-in-noise/Django_Model_Relationships_Methods_and_Properties#1]
https://github.com/lost-in-noise/Django_Model_Relationships_Methods_and_Properties/blob/80bbb8e9df1816c4d890e88d94212e83b5ae56fd/myproject/library/models.py#L22

ანუ თუ ამ პრონციპს გაყვები მაგალითად მერე ყოველთვის გეცოდინება რომ თუ მოკავშირე ფილდს ეძებ ყოველთვის მოდელის თავში იქნება და სხვაგან არ უნდა ეძებო

კიდევ უფრო მეტად გამართლებულია როდესაც რამდენიმე დეველოპერი მუშაობს პროექტზე ან ახალი წევრი ემატება გუნდს

**Comment by lost-in-noise** [comment]
ForeignKey ფილდი (author) მოდელის დასაწყისში გადავიტანე Book მოდელში.
ManyToManyField ფილდი (courses) მოდელის დასაწყისში გადავიტანე Student მოდელში.
